#!/usr/bin/env python3
"""Emit loud stubs for the symbols a link attempt left unresolved.

Every unresolved function becomes a body that reports its name and halts
(re4dc_missing), so a boot run stops at the first missing dependency with its
name on the console instead of jumping to address 0. Data symbols get a zeroed
block. The generated unit is a build product; the list of what it covers is
the honest statement of what the platform layer does not implement yet.

    gen_missing.py <unresolved-names> <out.cpp>

<unresolved-names>: one raw symbol per line (as sh-elf-nm prints it, with the
leading underscore of C symbols).
"""
import re
import sys

names = sorted({l.strip() for l in open(sys.argv[1]) if l.strip()})
with open(sys.argv[2], "w", newline="\n") as f:
    f.write("// generated by gen_missing.py: unresolved symbols as loud stubs\n")
    f.write('#include "re4dc_platform.h"\n\n')
    for i, n in enumerate(names):
        # Data-looking names (vtables/typeinfo) get storage; everything else a trap.
        if n.startswith("__ZTV") or n.startswith("__ZTI") or n.startswith("__ZTS"):
            f.write('extern "C" unsigned long re4dc_missing_data_%d[64] asm("%s");\n' % (i, n))
            f.write("unsigned long re4dc_missing_data_%d[64];\n" % i)
        else:
            f.write('extern "C" void re4dc_missing_fn_%d(void) asm("%s");\n' % (i, n))
            f.write('void re4dc_missing_fn_%d(void) { re4dc_missing("%s"); }\n' % (i, n))
print("missing stubs: %d" % len(names))
