#!/usr/bin/env python3
"""Generates the make rules and the unresolved-import stubs of the REL
modules that are linked into the Dreamcast image.

On the GameCube every stage REL (config/G4BE08/modules/<mod>/splits.txt) is
a separate link: its units, the stage's st<N>.cpp entry object and, for the
rooms of the stage the REL does not hold, imports the loader binds to the
module's _unresolved. Here each REL becomes one partially linked object
(sh-elf-ld -r) whose only global symbols are its renamed entry points, so
the rooms and helpers that several RELs define under the same name (r100 /
r10b readEvent, r119 / r11e koyaA_delete ...) do not collide, and the rooms
missing from the REL are stubs that call the module's unresolved handler,
which is what the GameCube loader binds them to.

    gen_modules.py <config modules dir> <src root> <obj dir> <out.mk> <mod>...

The unit list of a module is its splits.txt; em_wrap.cpp is the stage
modules' copy of src/st/em_wrap.cpp (config/G4BE08/modules.py).
"""
import os
import runpy
import re
import sys


def units(cfg, mod):
    text = open(os.path.join(cfg, mod, "splits.txt")).read()
    stage = mod.split("_")[0]
    out = []
    shared = {u[0]: u[2] for u in runpy.run_path(os.path.join(os.path.dirname(cfg), "modules.py"))["UNITS"].get(mod, []) if len(u) > 2 and u[2]}
    for name in re.findall(r"^%s/([A-Za-z0-9_]+\.cpp):" % re.escape(mod), text, re.M):
        if mod + "/" + name in shared:
            src = "src/" + shared[mod + "/" + name]
        elif name == "em_wrap.cpp":
            src = "src/st/em_wrap.cpp"
        else:
            src = "src/%s/%s" % (stage, name)
        if src not in out:
            out.append(src)
    return stage, out


def table_rooms(src_root, stage):
    """The rooms the stage entry object registers (st<N>.cpp setTbl)."""
    if not re.fullmatch(r"st[0-9]+", stage):
        return []
    text = open(os.path.join(src_root, "src", stage, stage + ".cpp")).read()
    return re.findall(r"set\(\s*\d+\s*,\s*(\w+)\s*,\s*(\w+)\s*\)", text)


def main():
    cfg, src_root, objdir, out_mk = sys.argv[1:5]
    mods = sys.argv[5:]
    mk = ["# generated by tools/gen_modules.py: one partially linked object per REL", ""]
    for mod in mods:
        stage, srcs = units(cfg, mod)
        present = set(os.path.basename(s)[:-4].lower() for s in srcs)
        stubs = []
        for init, mainf in table_rooms(src_root, stage):
            room = init[:-4].lower()  # R120Init -> r120
            if room not in present:
                stubs.append(init)
                stubs.append(mainf)
        moddir = os.path.join(objdir, "mod", mod)
        os.makedirs(moddir, exist_ok=True)
        stub_path = os.path.join(moddir, "unresolved.cpp")
        body = ["// generated by tools/gen_modules.py: rooms the %s REL does not hold" % mod,
                "// (the GameCube loader binds their imports to the module's _unresolved)",
                'extern "C" void %s_unresolved();' % mod]
        for fn in stubs:
            body.append("void %s() { %s_unresolved(); }" % (fn, mod))
        text = "\n".join(body) + "\n"
        if not os.path.exists(stub_path) or open(stub_path).read() != text:
            open(stub_path, "w").write(text)
        defs = " ".join("-D_%s=%s_%s" % (k, mod, k) for k in ("prolog", "epilog", "unresolved"))
        defs += " -D_ctors=re4dc_module_ctors -D_dtors=re4dc_module_dtors"
        objs = " ".join("$(OBJDIR)/mod/%s/%s.o" % (mod, s[:-4]) for s in srcs)
        mk += [
            "MOD_%s_OBJS = %s $(OBJDIR)/mod/%s/unresolved.o" % (mod, objs, mod),
            "$(OBJDIR)/mod/%s/%%.o: $(ROOT)/%%.cpp" % mod,
            "\t@mkdir -p $(dir $@)",
            "\tkos-c++ $(KOS_CFLAGS) $(GAME_CPPFLAGS) %s -MMD -MP -c $< -o $@" % defs,
            "$(OBJDIR)/mod/%s/unresolved.o: $(OBJDIR)/mod/%s/unresolved.cpp" % (mod, mod),
            "\tkos-c++ $(KOS_CFLAGS) $(GAME_CPPFLAGS) -c $< -o $@",
            "$(OBJDIR)/mod/%s.o: $(MOD_%s_OBJS) $(MODULES_MK)" % (mod, mod),
            "\tsh-elf-ld -r --force-group-allocation -EL -o $@.tmp $(MOD_%s_OBJS)" % mod,
            "\tsh-elf-objcopy -G _%s_prolog -G _%s_epilog $@.tmp $@" % (mod, mod),
            "\trm -f $@.tmp",
            "MODULE_OBJS += $(OBJDIR)/mod/%s.o" % mod,
            "-include $(MOD_%s_OBJS:.o=.d)" % mod,
            "",
        ]
    text = "\n".join(mk)
    if not os.path.exists(out_mk) or open(out_mk).read() != text:
        open(out_mk, "w").write(text)


if __name__ == "__main__":
    main()
