#!/usr/bin/env python3
"""Generates the make rules and the unresolved-import stubs of the REL
modules that are linked into the Dreamcast image.

On the GameCube every stage REL (config/G4BE08/modules/<mod>/splits.txt) is
a separate link: its units, the stage's st<N>.cpp entry object and, for the
rooms of the stage the REL does not hold, imports the loader binds to the
module's _unresolved. Here each REL becomes one partially linked object
(sh-elf-ld -r) whose only global symbols are its renamed entry points, so
the rooms and helpers that several RELs define under the same name (r100 /
r10b readEvent, r119 / r11e koyaA_delete ...) do not collide, and the rooms
missing from the REL are stubs that call the module's unresolved handler,
which is what the GameCube loader binds them to.

    gen_modules.py <config modules dir> <src root> <obj dir> <out.mk> <mod>...

The unit list of a module is its splits.txt; em_wrap.cpp is the stage
modules' copy of src/st/em_wrap.cpp (config/G4BE08/modules.py).
"""
import os
import runpy
import re
import sys


# Modules whose static constructors run on every link, as the GameCube REL
# _prolog does (the Sscrn sub screen: its model managers are .bss objects that
# a fresh link zeroes, so they must be constructed again per open). Their
# .init_array/.ctors input sections become the null-terminated list the
# module's own _prolog walks (re4dc_mod_<mod>_ctors). Destructors registered by
# those constructors (__cxa_atexit) go to re4dc_mod_<mod>_atexit and run from
# the module's _epilog list re4dc_mod_<mod>_dtors (platform/modules.cpp), so
# nothing accumulates in the KOS atexit list across opens.
PER_LINK_CTORS = {"Sscrn"}


def units(cfg, mod):
    text = open(os.path.join(cfg, mod, "splits.txt")).read()
    stage = mod.split("_")[0]
    out = []
    shared = {u[0]: u[2] for u in runpy.run_path(os.path.join(os.path.dirname(cfg), "modules.py"))["UNITS"].get(mod, []) if len(u) > 2 and u[2]}
    for name in re.findall(r"^%s/([A-Za-z0-9_]+\.cpp):" % re.escape(mod), text, re.M):
        if mod + "/" + name in shared:
            src = "src/" + shared[mod + "/" + name]
        elif name == "em_wrap.cpp":
            src = "src/st/em_wrap.cpp"
        else:
            src = "src/%s/%s" % (stage, name)
        if src not in out:
            out.append(src)
    return stage, out


def table_rooms(src_root, stage):
    """The rooms the stage entry object registers (st<N>.cpp setTbl)."""
    if not re.fullmatch(r"st[0-9]+", stage):
        return []
    text = open(os.path.join(src_root, "src", stage, stage + ".cpp")).read()
    return re.findall(r"set\(\s*\d+\s*,\s*(\w+)\s*,\s*(\w+)\s*\)", text)


def main():
    cfg, src_root, objdir, out_mk = sys.argv[1:5]
    mods = sys.argv[5:]
    mk = ["# generated by tools/gen_modules.py: one partially linked object per REL", ""]
    for mod in mods:
        if "=" in mod:  # <group>=<rel>+<rel>...: RELs that share one image copy (group_rules)
            mk += group_rules(cfg, objdir, mod); continue
        stage, srcs = units(cfg, mod)
        present = set(os.path.basename(s)[:-4].lower() for s in srcs)
        stubs = []
        for init, mainf in table_rooms(src_root, stage):
            room = init[:-4].lower()  # R120Init -> r120
            if room not in present:
                stubs.append(init)
                stubs.append(mainf)
        moddir = os.path.join(objdir, "mod", mod)
        os.makedirs(moddir, exist_ok=True)
        stub_path = os.path.join(moddir, "unresolved.cpp")
        body = ["// generated by tools/gen_modules.py: rooms the %s REL does not hold" % mod,
                "// (the GameCube loader binds their imports to the module's _unresolved)",
                'extern "C" void %s_unresolved();' % mod]
        for fn in stubs:
            body.append("void %s() { %s_unresolved(); }" % (fn, mod))
        text = "\n".join(body) + "\n"
        if not os.path.exists(stub_path) or open(stub_path).read() != text:
            open(stub_path, "w").write(text)
        defs = " ".join("-D_%s=%s_%s" % (k, mod, k) for k in ("prolog", "epilog", "unresolved"))
        per_link = mod in PER_LINK_CTORS
        if per_link:
            defs += " -D_ctors=re4dc_mod_%s_ctors -D_dtors=re4dc_mod_%s_dtors" % (mod, mod)
        else:
            defs += " -D_ctors=re4dc_module_ctors -D_dtors=re4dc_module_dtors"
        objs = " ".join("$(OBJDIR)/mod/%s/%s.o" % (mod, s[:-4]) for s in srcs)
        # Link-time state of the REL. A GameCube OSLink of a freshly read REL
        # sees pristine .data and a zeroed .bss; here the module is resident,
        # so its writable sections are gathered into one span each, bounded by
        # symbols platform/modules.cpp uses to restore them on a fresh link.
        # The .bss span also reserves the pristine .data copy (bss, not image).
        state = ["_re4dc_mod_%s_%s" % (mod, k) for k in
                 ("data", "data_end", "bss", "bss_end", "pristine")]
        script_path = os.path.join(moddir, "state.ld")
        script = "\n".join([
            "/* generated by tools/gen_modules.py: the %s REL's writable state */" % mod,
            "SECTIONS {",
            "  .data.re4dc_module.%s : {" % mod,
            "    %s = .;" % state[0],
            "    *(.data .data.*)",
            "    %s = .;" % state[1],
            "  }",
            "  .bss.re4dc_module.%s (NOLOAD) : {" % mod,
            "    %s = .;" % state[2],
            "    *(.bss .bss.* COMMON)",
            "    %s = .;" % state[3],
            "    . = ALIGN(4);",
            "    %s = .;" % state[4],
            "    . += SIZEOF(.data.re4dc_module.%s);" % mod,
            "  }",
        ] + ([
            "  .rodata.re4dc_module_ctors.%s : {" % mod,
            "    _re4dc_mod_%s_ctors = .;" % mod,
            "    *(.init_array .init_array.* .ctors .ctors.*)",
            "    LONG(0)",
            "  }",
        ] if per_link else []) + [
            "}",
        ]) + "\n"
        if not os.path.exists(script_path) or open(script_path).read() != script:
            open(script_path, "w").write(script)
        keep = " ".join("-G %s" % s for s in ["_%s_prolog" % mod, "_%s_epilog" % mod] + state)
        mk += [
            "MOD_%s_OBJS = %s $(OBJDIR)/mod/%s/unresolved.o" % (mod, objs, mod),
            "$(OBJDIR)/mod/%s/%%.o: $(ROOT)/%%.cpp" % mod,
            "\t@mkdir -p $(dir $@)",
            "\tkos-c++ $(KOS_CFLAGS) $(GAME_CPPFLAGS) %s -MMD -MP -c $< -o $@" % defs,
            "$(OBJDIR)/mod/%s/unresolved.o: $(OBJDIR)/mod/%s/unresolved.cpp" % (mod, mod),
            "\tkos-c++ $(KOS_CFLAGS) $(GAME_CPPFLAGS) -c $< -o $@",
            "$(OBJDIR)/mod/%s.o: $(MOD_%s_OBJS) $(MODULES_MK) $(OBJDIR)/mod/%s/state.ld" % (mod, mod, mod),
            "\tsh-elf-ld -r -d --force-group-allocation -EL -T $(OBJDIR)/mod/%s/state.ld -o $@.tmp $(MOD_%s_OBJS)" % (mod, mod),
            # The prolog walks an empty _ctors list: constructors that the image
            # ran once at start would not re-run per link as on the GameCube.
            "\t@if sh-elf-objdump -h $@.tmp | awk '$$2 ~ /^\\.(ctors|dtors|init_array|fini_array)/ {f=1} END {exit !f}'; then "
            "echo '%s: REL static constructors/destructors need per-link execution' >&2; rm -f $@.tmp; exit 1; fi" % mod,
            "\t@if sh-elf-nm $@.tmp | awk '$$2 == \"C\" {f=1} END {exit !f}'; then "
            "echo '%s: common symbols escape the REL state span' >&2; rm -f $@.tmp; exit 1; fi" % mod,
            # PowerPC link names the module's own sources call through asm("name")
            # (leonModelInit, numDisp, quit__9ssDbgPzzl) bind to their SH-4
            # definitions here, as tools/link.sh does for the image: once the
            # module's symbols are local the image link can no longer see them.
            *([
                "\t@sh-elf-nm $@.tmp | grep -E ' [TDBWRV] ' | awk '{print $$3}' | sort -u > $@.def",
                "\t@sh-elf-c++filt < $@.def | paste $@.def - > $@.pairs",
                "\t@sh-elf-nm $@.tmp | grep -E ' U ' | awk '{print $$2}' | sort -u | comm -23 - $@.def > $@.undef",
                "\t@python3 tools/gen_aliases.py $@.undef $@.pairs $@.aliases.ld",
                "\t@if [ -s $@.aliases.ld ]; then sh-elf-ld -r -EL -o $@.tmp2 $@.tmp $@.aliases.ld && mv $@.tmp2 $@.tmp; fi",
                "\t@rm -f $@.def $@.pairs $@.undef",
            ] if per_link else []),
            *([
                "\t@if sh-elf-nm $@.tmp | awk '$$1 == \"U\" && $$2 == \"_atexit\" {f=1} END {exit !f}'; then "
                "echo '%s: static destructors registered with atexit' >&2; rm -f $@.tmp; exit 1; fi" % mod,
            ] if per_link else []),
            "\tsh-elf-objcopy %s%s $@.tmp $@" % (keep, " --redefine-sym ___cxa_atexit=_re4dc_mod_%s_atexit" % mod if per_link else ""),
            "\trm -f $@.tmp",
            "MODULE_OBJS += $(OBJDIR)/mod/%s.o" % mod,
            "-include $(MOD_%s_OBJS:.o=.d)" % mod,
            "",
        ]
    text = "\n".join(mk)
    if not os.path.exists(out_mk) or open(out_mk).read() != text:
        open(out_mk, "w").write(text)


def group_rules(cfg, objdir, spec):
    """<group>=<rel>+<rel>...: RELs built from the same shared units (the Ganado modules em10..em20
    are all em10.cpp + em10_tmpl.cpp + their own <em>_set.cpp) as ONE partially linked object, so
    the image carries one copy of the shared code (~250 KB for em10.cpp) instead of one per REL.

    Each member keeps its own entry points (_<rel>_prolog/_epilog/_unresolved, from its own units)
    and its own REL id in platform/modules.cpp. The writable state (all members' .data/.bss) is one
    span; every member's span symbols name it, so a fresh link of any member restores the span's
    pristine .data and zeroes its .bss, as a newly read REL has. Two members linked at the same time
    would share the shared units' statics (em10.cpp's Em10SetFunc among them); platform/modules.cpp
    logs that case. Stage modules (rooms, _unresolved stubs) cannot be grouped."""
    group, rels = spec.split("=")
    rels = rels.split("+")
    per = [(r, units(cfg, r)) for r in rels]
    for r, (stage, _) in per:
        if re.fullmatch(r"st[0-9]+", stage):
            sys.exit("gen_modules.py: stage module %s cannot be grouped" % r)
    shared = [s for s in per[0][1][1] if all(s in u for _, (_, u) in per)]
    gdir = os.path.join(objdir, "mod", group)
    os.makedirs(gdir, exist_ok=True)

    def defs(r):
        return " ".join("-D_%s=%s_%s" % (k, r, k) for k in ("prolog", "epilog", "unresolved")) + \
            " -D_ctors=re4dc_module_ctors -D_dtors=re4dc_module_dtors"

    objs = ["$(OBJDIR)/mod/%s/shared/%s.o" % (group, s[:-4]) for s in shared]
    rules = ["$(OBJDIR)/mod/%s/shared/%%.o: $(ROOT)/%%.cpp" % group,
             "\t@mkdir -p $(dir $@)",
             # the shared units reference no entry-point name; any member's defines compile them
             "\tkos-c++ $(KOS_CFLAGS) $(GAME_CPPFLAGS) %s -MMD -MP -c $< -o $@" % defs(rels[0])]
    for r, (stage, srcs) in per:
        os.makedirs(os.path.join(gdir, r), exist_ok=True)
        stub_path = os.path.join(gdir, r, "unresolved.cpp")
        text = "// generated by tools/gen_modules.py: the %s REL holds no rooms\nextern \"C\" void %s_unresolved();\n" % (r, r)
        if not os.path.exists(stub_path) or open(stub_path).read() != text:
            open(stub_path, "w").write(text)
        objs += ["$(OBJDIR)/mod/%s/%s/%s.o" % (group, r, s[:-4]) for s in srcs if s not in shared]
        objs.append("$(OBJDIR)/mod/%s/%s/unresolved.o" % (group, r))
        rules += ["$(OBJDIR)/mod/%s/%s/%%.o: $(ROOT)/%%.cpp" % (group, r),
                  "\t@mkdir -p $(dir $@)",
                  "\tkos-c++ $(KOS_CFLAGS) $(GAME_CPPFLAGS) %s -MMD -MP -c $< -o $@" % defs(r),
                  "$(OBJDIR)/mod/%s/%s/unresolved.o: $(OBJDIR)/mod/%s/%s/unresolved.cpp" % (group, r, group, r),
                  "\tkos-c++ $(KOS_CFLAGS) $(GAME_CPPFLAGS) -c $< -o $@"]
    keys = ("data", "data_end", "bss", "bss_end", "pristine")
    names = [group] + rels
    sym = lambda k: " ".join("_re4dc_mod_%s_%s = .;" % (n, k) for n in names)
    script = "\n".join([
        "/* generated by tools/gen_modules.py: the writable state shared by the %s RELs */" % "/".join(rels),
        "SECTIONS {",
        "  .data.re4dc_module.%s : {" % group,
        "    %s" % sym("data"),
        "    *(.data .data.*)",
        "    %s" % sym("data_end"),
        "  }",
        "  .bss.re4dc_module.%s (NOLOAD) : {" % group,
        "    %s" % sym("bss"),
        "    *(.bss .bss.* COMMON)",
        "    %s" % sym("bss_end"),
        "    . = ALIGN(4);",
        "    %s" % sym("pristine"),
        "    . += SIZEOF(.data.re4dc_module.%s);" % group,
        "  }",
        "}",
    ]) + "\n"
    script_path = os.path.join(gdir, "state.ld")
    if not os.path.exists(script_path) or open(script_path).read() != script:
        open(script_path, "w").write(script)
    keep = " ".join("-G %s" % s for s in
                    ["_%s_%s" % (r, k) for r in rels for k in ("prolog", "epilog")] +
                    ["_re4dc_mod_%s_%s" % (n, k) for n in names for k in keys])
    return [
        "MOD_%s_OBJS = %s" % (group, " ".join(objs)),
    ] + rules + [
        "$(OBJDIR)/mod/%s.o: $(MOD_%s_OBJS) $(MODULES_MK) $(OBJDIR)/mod/%s/state.ld" % (group, group, group),
        "\tsh-elf-ld -r -d --force-group-allocation -EL -T $(OBJDIR)/mod/%s/state.ld -o $@.tmp $(MOD_%s_OBJS)" % (group, group),
        "\t@if sh-elf-objdump -h $@.tmp | awk '$$2 ~ /^\\.(ctors|dtors|init_array|fini_array)/ {f=1} END {exit !f}'; then "
        "echo '%s: REL static constructors/destructors need per-link execution' >&2; rm -f $@.tmp; exit 1; fi" % group,
        "\t@if sh-elf-nm $@.tmp | awk '$$2 == \"C\" {f=1} END {exit !f}'; then "
        "echo '%s: common symbols escape the REL state span' >&2; rm -f $@.tmp; exit 1; fi" % group,
        "\tsh-elf-objcopy %s $@.tmp $@" % keep,
        "\trm -f $@.tmp",
        "MODULE_OBJS += $(OBJDIR)/mod/%s.o" % group,
        "-include $(MOD_%s_OBJS:.o=.d)" % group,
        "",
    ]


if __name__ == "__main__":
    main()
