"""Read a room's .LIT and emit the fog, background and light table for a cut.

The layout is the game's own, from include/light.h:

    cLit      u16 CutNum, u8 Version, u8 nMaxLight, then u32[CutNum] cut offsets
    cut       cLightEnv (0x104) followed by nLight cLightWork (0x12C each)

Everything is big-endian: this is GameCube data.

The values the runtime needs are the ones r100's constants were transcribed from
by hand -- fog start and end, the background colour, the far-play ratio, and the
per-light position, radius, colour, intensity, type and direction. Reading them
instead of transcribing them is what lets a second room have its own.

    convert_lit.py <file.lit> [--cut N] [--scale 0.001] [--header out.hpp]
                   [--name R101]
"""
import argparse
import pathlib
import struct

ENV_SIZE = 0x104
WORK_SIZE = 0x12C


def be(fmt, data, offset):
    return struct.unpack_from(">" + fmt, data, offset)


def read_env(data, offset):
    nlight, = be("I", data, offset + 0x04)
    fog_type, = be("i", data, offset + 0x08)
    fog_start, fog_end = be("ff", data, offset + 0x0C)
    bg = be("4B", data, offset + 0x14)
    far_play, = be("f", data, offset + 0x44)
    ambient_scr = be("4B", data, offset + 0x00)
    ambient_em = be("4B", data, offset + 0xFC)
    ambient_esp = be("4B", data, offset + 0x100)
    return {
        "lights": nlight, "fog_type": fog_type,
        "fog_start": fog_start, "fog_end": fog_end,
        "bg": bg, "far_play_ratio": far_play,
        "ambient_screen": ambient_scr, "ambient_model": ambient_em,
        "ambient_effect": ambient_esp,
    }


def read_light(data, offset):
    # The runtime's SourceLight takes its type from xD (the spot-type byte) and
    # its enable mask from xF, not from the Type field, which is the game's
    # per-type move handler. Verified against r100: the ten entries hand
    # transcribed into kSourceLights carry exactly these xD and xF values.
    be_flag, spot_type, move_type, enable_mask = be("4B", data, offset + 0x00)
    px, py, pz = be("fff", data, offset + 0x04)
    radius, = be("f", data, offset + 0x10)
    col = be("4B", data, offset + 0x14)
    intensity, = be("f", data, offset + 0x18)
    parent_type, kind, attribute, priority = be("4B", data, offset + 0x1C)
    nx, ny, nz = be("fff", data, offset + 0x2C)
    # A0 is the spot cutoff for a spot light and a flag word for a parallel
    # one, which is the same four bytes read two ways.
    cutoff, = be("f", data, offset + 0x2C + 0x0C)
    spot_flags, = be("I", data, offset + 0x2C + 0x0C)
    return {
        "be_flag": be_flag, "type": spot_type, "move_type": move_type,
        "enable_mask": enable_mask, "pos": (px, py, pz), "radius": radius,
        "colour": col, "intensity": intensity, "kind": kind,
        "attribute": attribute, "priority": priority,
        "direction": (nx, ny, nz), "cutoff": cutoff,
        "view_space": bool(spot_flags & 1),
        "empty": radius == 0.0 and col[:3] == (0, 0, 0),
    }


def read_cut(path, cut_no):
    data = path.read_bytes()
    cut_num, version, max_light = be("HBB", data, 0)
    offsets = list(be("%dI" % cut_num, data, 4)) if cut_num else []
    if cut_no >= cut_num or offsets[cut_no] == 0:
        raise SystemExit("cut %d is absent; %d cuts, offsets %s"
                         % (cut_no, cut_num, offsets[:8]))
    base = offsets[cut_no]
    env = read_env(data, base)
    lights = [read_light(data, base + ENV_SIZE + i * WORK_SIZE)
              for i in range(env["lights"])]
    return {"cuts": cut_num, "version": version, "max_lights": max_light,
            "env": env, "lights": lights}


def emit_header(cut, name, scale, source):
    env = cut["env"]
    out = []
    out.append("#pragma once")
    out.append("")
    out.append("// Generated by tools/convert_lit.py from %s, cut 0." % source)
    out.append("// Do not edit: re-run the converter. Positions and radii are")
    out.append("// scaled from source units to metres; colours, intensity,")
    out.append("// direction and type are carried through unchanged.")
    out.append("")
    out.append("// Included inside main.cpp's anonymous namespace, so the names are the")
    out.append("// ones the scene machinery already uses. One scene's header is included")
    out.append("// per build; they never coexist.")
    out.append("")
    out.append("constexpr float kSourceFogStartDistance = %.6ff;"
               % (env["fog_start"] * scale))
    out.append("constexpr float kFogEndDistance = %.6ff;"
               % (env["fog_end"] * scale))
    # cLightMgr shortens the gameplay far plane to fogEnd * (1 - ratio) + 1 in
    # source units.
    far = (env["fog_end"] * (1.0 - env["far_play_ratio"]) + 1.0) * scale
    out.append("constexpr float kFarClipDistance = %.6ff;" % far)
    out.append("constexpr float kSourceFarPlayRatio = %.6ff;"
               % env["far_play_ratio"])
    r, g, b, _ = env["bg"]
    out.append("constexpr float kBackgroundRed = %d.0f / 255.0f;" % r)
    out.append("constexpr float kBackgroundGreen = %d.0f / 255.0f;" % g)
    out.append("constexpr float kBackgroundBlue = %d.0f / 255.0f;" % b)
    ar, ag, ab, _ = env["ambient_screen"]
    out.append("constexpr float kSourceRoomAmbientRed = %d.0f / 255.0f;" % ar)
    out.append("constexpr float kSourceRoomAmbientGreen = %d.0f / 255.0f;" % ag)
    out.append("constexpr float kSourceRoomAmbientBlue = %d.0f / 255.0f;" % ab)
    out.append("")
    live = [l for l in cut["lights"] if not l["empty"]]
    out.append("// %d authored lights in this cut, of %d slots. Empty slots are"
               % (len(live), len(cut["lights"])))
    out.append("// dropped; nothing else is filtered, so the reach of a light is")
    out.append("// decided by the runtime's own radius and volume tests rather")
    out.append("// than by a judgement made here.")
    out.append("constexpr SourceLight kSourceLights[] = {")
    for index, light in enumerate(cut["lights"]):
        if light["empty"]:
            continue
        px, py, pz = (v * scale for v in light["pos"])
        nx, ny, nz = light["direction"]
        cr, cg, cb, _ = light["colour"]
        out.append("    // slot %d, BeFlag %d, move type %d"
                   % (index, light["be_flag"], light["move_type"]))
        out.append("    {%du, %s, %.6ff, %.6ff, %.6ff, %.6ff,"
                   % (light["type"], "true" if light["view_space"] else "false",
                      px, py, pz, light["radius"] * scale))
        out.append("     %d.0f / 255.0f, %d.0f / 255.0f, %d.0f / 255.0f, %.6ff,"
                   % (cr, cg, cb, light["intensity"]))
        out.append("     %.6ff, %.6ff, %.6ff, %.6ff, %du, 0x%02xU},"
                   % (nx, ny, nz,
                      light["cutoff"] if light["type"] == 3 else 0.0,
                      index, light["enable_mask"]))
    out.append("};")
    out.append("")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input", type=pathlib.Path)
    ap.add_argument("--cut", type=int, default=0)
    ap.add_argument("--scale", type=float, default=0.001)
    ap.add_argument("--header", type=pathlib.Path)
    ap.add_argument("--name", default="ROOM")
    args = ap.parse_args()

    cut = read_cut(args.input, args.cut)
    env = cut["env"]
    print("%s: %d cuts, version %d, max lights %d" %
          (args.input.name, cut["cuts"], cut["version"], cut["max_lights"]))
    print("  cut %d: %d lights, fog type %d, fog %.1f..%.1f, far play %.3f, "
          "bg %s" % (args.cut, env["lights"], env["fog_type"],
                     env["fog_start"], env["fog_end"], env["far_play_ratio"],
                     env["bg"][:3]))
    print("  ambient screen %s model %s effect %s" %
          (env["ambient_screen"][:3], env["ambient_model"][:3],
           env["ambient_effect"][:3]))
    for index, light in enumerate(cut["lights"]):
        if light["empty"]:
            continue
        print("   slot %2d type=%d mask=0x%02x be=%d view=%d pos=(%.1f %.1f %.1f) "
              "r=%.1f col=%s i=%.3f cutoff=%.2f" %
              (index, light["type"], light["enable_mask"], light["be_flag"],
               light["view_space"], light["pos"][0], light["pos"][1],
               light["pos"][2], light["radius"], light["colour"][:3],
               light["intensity"],
               light["cutoff"] if light["type"] == 3 else 0.0))
    if args.header:
        args.header.write_text(
            emit_header(cut, args.name, args.scale, args.input.name),
            encoding="utf-8")
        print("wrote %s" % args.header)


if __name__ == "__main__":
    main()
